FROM node:alpine

# Set the working directory for the frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the container
COPY ./package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend source code to the container
COPY ./ .

EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]


